name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/mobile/**

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set-up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: pnpm/action-setup@v2
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build JS
        run: pnpm --filter pornote-mobile run build

      - name: Build APK bundle
        run: cd android && gradle bundle

      - name: Upload APK bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60