name: Build Android (beta)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'platforms/mobile/**'
      - '!packages/README.md'
      - '!packages/**/README.md'
      - '!platforms/mobile/README.md'

jobs:
  build:
    if: ${{ false }}  # Disable since @pawnote/mobile is not ready.

    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set-up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set-up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Set-up pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build @pawnote/api
        run: pnpm --filter @pawnote/api run build

      - name: Build @pawnote/i18n
        run: pnpm --filter @pawnote/i18n run build

      - name: Build @pawnote/client
        run: pnpm --filter @pawnote/client run build

      - name: Build @pawnote/mobile
        run: pnpm --filter @pawnote/mobile run build

      - name: Build APK
        working-directory: packages/mobile/android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: packages/mobile/android/app/build/outputs/apk/debug/*.apk
          retention-days: 60
