name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/mobile/**

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set-up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Set-up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Set-up pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build JS
        run: pnpm --filter pornote-mobile run build

      - name: Build APK bundle
        working-directory: packages/mobile/android
        run: ./gradlew assembleRelease

      - name: Upload APK bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: packages/mobile/android/app/build/outputs/apk/release/*.apk
          retention-days: 60
