name: Release everything

on:  
  push:
    tags:
      - '*'

jobs:
  web-deploy:
    if: ${{ false }}  # Disable since @pawnote/web is not ready.

    name: Deploy @pawnote/web to Vercel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build @pawnote/api
        run: pnpm --filter @pawnote/api run build

      - name: Build @pawnote/i18n
        run: pnpm --filter @pawnote/i18n run build

      - name: Build @pawnote/web
        run: pnpm --filter @pawnote/web run build

      - name: Deploy prebuilt @pawnote/web
        uses: amondnet/vercel-action@v25
        with:
          working-directory: platforms/web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          vercel-args: "--prod"
          github-comment: false

